### ISSUE TITLE
How to run on graphs with heterophily?

### ISSUE THREAD

**Issue by ghost** [GemsLab/H2GCN#1]
Hi,
I'd like to ask how to run the code on graphs with heterophily? e.g., Texas, Actor

**Comment by jiong-zhu** [comment]
Hi, thank you for your interest! Please use the script in `experiments/h2gcn/scripts/get-real-geomgcn.sh` to download the corresponding datasets (including all datasets listed in Table 5, except Cora Full), then you can use the following commands to run H2GCN:

```
cd experiments/h2gcn/
python run_hgcn_experiments.py -c configs/real-geomgcn/h2gcn.json run
```

You can check out the readme for more details about the usage of these commands (including how to run the other models).

**Comment by ghost** [comment]
Thank you!
