### ISSUE TITLE
ImportError: cannot import name 'FlowProject' from 'flow'

### ISSUE THREAD

**Issue by ScottHoang** [GemsLab/H2GCN#10]
While trying to recreate experiments from experiments/h2gcn/
I am encountering this issue
ImportError: cannot import name 'FlowProject' from 'flow'
I cannot resolve it; can you help?

**Comment by jiong-zhu** [comment]
Hi Scott, have you followed our README to install specific version of `signac`? 
```
pip install signac==1.1 signac-flow==0.7.1 signac-dashboard
```

**Comment by ScottHoang** [comment]
ah, this was indeed the problem. It is fixed.
