### ISSUE TITLE
About heterophilic datasets

### ISSUE THREAD

**Issue by liu-jc** [GemsLab/H2GCN#2]
Firstly, thanks for your impressive work and the source code. I downloaded the datasets based on your script. For heterophilic datasets, I found there are two files in data_source folder (one for graph edges and one for node&feature&label). I would like to know are these two files the same as here (https://github.com/graphdml-uiuc-jlu/geom-gcn/tree/master/new_data)? Thanks!

**Comment by jiong-zhu** [comment]
Thank you for your interest in our work! Yes, these files are the same as the files in the [Geom-GCN repo](https://github.com/graphdml-uiuc-jlu/geom-gcn) you mentioned.

**Comment by liu-jc** [comment]
Thank you for your reply!
