### ISSUE TITLE
about downloading dataset

### ISSUE THREAD

**Issue by ShunliRen** [GemsLab/H2GCN#3]
thanks for your impressive work!
When I download the dataset, it seems that  I can't connect to https://umich.app.box.com. Would you like to give me some suggestion about it ?
thx!
`--2021-01-11 19:04:34--  (try: 4)  https://umich.app.box.com/public/static/oerjpreqd1u1cn481mk1m788fd4ahcvv.gz

Connecting to umich.app.box.com (umich.app.box.com)|2001::42dc:932f|:443... failed: Connection timed out.
Retrying.`

**Comment by jiong-zhu** [comment]
Thank you for your interest in our work! I think the most likely reason is that this URL cannot be directly accessed within mainland China. As an alternative, you could try to manually download the dataset with a proxy server or VPN and place it in the `<project_root>/experiments/h2gcn/` folder, and follow [line 9-11 of the script](https://github.com/GemsLab/H2GCN/blob/6e42eec34d854c1adf9e01c2c26985d03262d9bc/experiments/h2gcn/scripts/get-syn-cora.sh#L9). You may also try to setup a proxy server for `wget`.

**Comment by ShunliRen** [comment]
Thanks for your suggestion!
