### ISSUE TITLE
Can not run H2GCN on Actor, WebKB and Wikipedia Dataset

### ISSUE THREAD

**Issue by AmitRoy7781** [GemsLab/H2GCN#7]
Hello, 

According to your repository you have provided the citation (cora, citeseer, pubmed) datasets. I want to reproduce the results of H2GCN in Actor, WebKB (Cornell, Texas, Wisconsin) and Wikipedia (Chameleon, Squirrel) datasets. 

But the citation datasets are transformed into .x, .y, .allx, .ally, .graph, .test.index in these format while other datasets mentioned above are not available in internet in these format. 

Can you please provide the utility code which you used to load these datasets to run H2GCN on them?

**Comment by jiong-zhu** [comment]
Thank you for your interest in our work!

We have actually transformed these datasets into `.x, .y, .allx, .ally, .graph, .test.index` files. If you download the archive from the URL in [the second line of this file](https://github.com/GemsLab/H2GCN/blob/6e42eec34d854c1adf9e01c2c26985d03262d9bc/experiments/h2gcn/scripts/get-real-geomgcn.sh#L2) and unzip it, you should be able to find files corresponding to each training, validation and test split as provided in the GeomGCN repo in paths similar to `workspace/*/features/*/splits/*`, where `*` represents some hash strings. You should be able to get more sense of the file structures once you get a chance to roam through these folders. 

The code we use to load the datasets are in [this file](https://github.com/GemsLab/H2GCN/blob/6e42eec34d854c1adf9e01c2c26985d03262d9bc/h2gcn/datasets/_dataset.py).

**Comment by ScottHoang** [comment]
Hi, I am having a similar issue running your code.
running the bash to download data files resulted in this error:
gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
Can you help?

**Comment by jiong-zhu** [comment]
> Hi, I am having a similar issue running your code.
> running the bash to download data files resulted in this error:
> gzip: stdin: not in gzip format
> tar: Child returned status 1
> tar: Error is not recoverable: exiting now
> Can you help?

Resolved in https://github.com/GemsLab/H2GCN/issues/9#issuecomment-1104445894.
