### ISSUE TITLE
About downloading geom-gcn datasets

### ISSUE THREAD

**Issue by ScottHoang** [GemsLab/H2GCN#9]
Hi, I cannot download geom-gcn datasets (texas, Wisconsin, Cornell) using provided scripts.
Can you help?

**Comment by jiong-zhu** [comment]
Hi Scott, thank you for your interest in our work. It seems that Google Drive has made some updates on their server, and I have updated the scripts for downloading the datasets using [`gdown`](https://github.com/wkentaro/gdown). 

If this mechanism unfortunately broke again in the future, it is also possible to download the dataset manually using the URL in Line 2 of the script, and follow the rest of the script to unzip it.
